service:
  name: opcua-cloud-gateway
  environment: dev

connectivity:
  opcua_source:
    endpoint_url: "opc.tcp://edge-gateway.local:4840"
    username: "${OPCUA_USER}"
    password: "${OPCUA_PASS}"

performance_targets:
  tags_per_second: 100000
  alarms_per_second: 5000
  p99_latency_ms: 500

load_profiles:
  - name: baseline
    tags_per_second: 50000
    alarms_per_second: 1000
    duration_seconds: 10

  - name: target
    tags_per_second: 100000
    alarms_per_second: 5000
    duration_seconds: 15

providers:
  active: "azure"
  azure:
    region: "eastus"
    vm_size: "Standard_D8s_v5"
