server:
  port: 8080

aws:
  region: us-east-1
  ecs:
    clusterArn: arn:aws:ecs:us-east-1:770404292192:cluster/opcua-cluster
    taskDefinitionArn: arn:aws:ecs:us-east-1:770404292192:task-definition/opcua-demo-task:6
    subnets:
      - subnet-049e2eaa45e549325
      - subnet-039ed173b7f91919e
    securityGroups:
      - sg-0ec837bdddadf3ee8
    assignPublicIp: ENABLED

  elbv2:
    nlbDns: opcua-nlb-103856889438b10c.elb.us-east-1.amazonaws.com

orchestrator:
  containerName: opcua-demo
  containerPort: 4840
  waitForRunningSeconds: 120   
  healthWaitSeconds: 240      
  baseExternalPort: 20001
